import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom, Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import { Chat, ChatMessage } from './chat';

@Injectable({ providedIn: 'root' })
export class ChatbotService {
  private chatsEndpoint = '/api/chatbot/chats';
  private http = inject(HttpClient);

  getChats(runId: number, workgroupId: number): Observable<Chat[]> {
    return this.http.get<Chat[]>(`${this.chatsEndpoint}/${runId}/${workgroupId}`).pipe(
      map((chats) => chats.filter((chat) => !chat.deleted) || []),
      catchError(() => of([]))
    );
  }

  createChat(runId: number, workgroupId: number, chatTitle: string): Promise<Chat> {
    const newChat: Chat = {
      id: null, // id will be generated by the server
      title: chatTitle,
      messages: [
        new ChatMessage('system', 'You are a helpful assistant. Be polite and concise.', null)
      ],
      createdAt: new Date(),
      lastUpdated: new Date(),
      deleted: false
    };
    return firstValueFrom(
      this.http.post<Chat>(`${this.chatsEndpoint}/${runId}/${workgroupId}`, newChat)
    );
  }

  updateChat(runId: number, workgroupId: number, chat: Chat): Promise<Chat> {
    return firstValueFrom(
      this.http.put<Chat>(`${this.chatsEndpoint}/${runId}/${workgroupId}/${chat.id}`, chat)
    );
  }

  deleteChat(runId: number, workgroupId: number, chatId: string): Promise<void> {
    return firstValueFrom(
      this.http.delete<void>(`${this.chatsEndpoint}/${runId}/${workgroupId}/${chatId}`)
    );
  }
}
