import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom, Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';

export interface Chat {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: Date;
  lastUpdated: Date;
  deleted: boolean;
}

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: Date;
}

@Injectable({ providedIn: 'root' })
export class ChatbotService {
  private chatGptEndpoint = '/api/chat-gpt';
  private chatsEndpoint = '/api/chatbot/chats';
  private http = inject(HttpClient);

  /**
   * Sends a message to the chat-gpt endpoint.
   * @param conversationHistory The conversation history.
   * @returns A promise that resolves to the response from the chat-gpt endpoint.
   */
  async sendMessage(conversationHistory: ChatMessage[]): Promise<string> {
    const payload = {
      messages: conversationHistory.map((msg) => ({
        role: msg.role,
        content: msg.content
      })),
      model: 'gpt-3.5-turbo'
    };
    try {
      const response = await firstValueFrom(
        this.http.post<any>(`${this.chatGptEndpoint}`, payload)
      );
      return response.choices[0].message.content;
    } catch (error) {
      console.error('Error calling chat-gpt endpoint:', error);
      throw error;
    }
  }

  getChats(runId: number, workgroupId: number): Observable<Chat[]> {
    return this.http.get<Chat[]>(`${this.chatsEndpoint}/${runId}/${workgroupId}`).pipe(
      map((chats) => chats.filter((chat) => !chat.deleted) || []),
      catchError(() => of([]))
    );
  }

  createChat(runId: number, workgroupId: number, chatTitle: string): Promise<Chat> {
    const newChat: Chat = {
      id: null, // id will be generated by the server
      title: chatTitle,
      messages: [
        {
          role: 'system',
          content: 'You are a helpful assistant. Be polite and concise.'
        }
      ],
      createdAt: new Date(),
      lastUpdated: new Date(),
      deleted: false
    };
    return firstValueFrom(
      this.http.post<Chat>(`${this.chatsEndpoint}/${runId}/${workgroupId}`, newChat)
    );
  }

  updateChat(runId: number, workgroupId: number, chat: Chat): Promise<Chat> {
    return firstValueFrom(
      this.http.put<Chat>(`${this.chatsEndpoint}/${runId}/${workgroupId}/${chat.id}`, chat)
    );
  }

  deleteChat(runId: number, workgroupId: number, chatId: string): Promise<void> {
    return firstValueFrom(
      this.http.delete<void>(`${this.chatsEndpoint}/${runId}/${workgroupId}/${chatId}`)
    );
  }
}
