name: Build
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Run CodeBuild
        id: code-build
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: wise-client-github-actions-project
      - run: echo ${{steps.code-build.outputs.aws-build-id}}
