name: Generate messages
on:
  pull_request:
    branches:
      - develop
jobs:
  generate-messages:
    runs-on: ubuntu-latest
    steps:
      - name: List containers
        run: docker ps -a
      - name: Generate messages
        run: docker exec -it wise-client npm run extract-i18n
