name: Generate messages
on:
  pull_request:
    branches:
      - develop
jobs:
  generate-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Check working directory
        run: pwd
      - name: Docker compose
        run: docker compose up
      - name: Generate messages
        run: docker exec -it wise-client npm run extract-i18n
