name: Non-develop branch PR workflows
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!develop'
jobs:
  generate-messages:
    uses: WISE-Community/WISE-Client/.github/workflows/generate-messages.yml@develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  test-coverage:
    needs: generate-messages
    uses: WISE-Community/WISE-Client/.github/workflows/test-coverage.yml@develop
    secrets:
      test_reporter: ${{secrets.CC_TEST_REPORTER_ID}}
