name: Non-develop branch PR workflows
on:
  pull_request:
    branches:
      - '**'
      - '!develop'
jobs:
  test-coverage:
    uses: WISE-Community/WISE-Client/.github/workflows/test-coverage.yml@develop

  generate-messages:
    needs: test-coverage
    uses: WISE-Community/WISE-Client/.github/workflows/generate-messages.yml@actions-fails-on-fork
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
