name: Test coverage
permissions:
  id-token: write
on:
  workflow_call:
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run test-coverage
      - uses: qltysh/qlty-action/coverage@v2
        with:
          # Disables OIDC automatically if the PR comes from an outside fork
          oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
          files: ${{github.workspace}}/coverage/lcov.info
