name: Test coverage
permissions:
  id-token: write
on:
  workflow_call:
  push:
    branches: [gh-actions-update-node-version-24]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run test-coverage
      - uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: ${{github.workspace}}/coverage/lcov.info
