name: Test coverage
permissions:
  id-token: write
on:
  workflow_call:
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run test-coverage
      - uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: ${{github.workspace}}/coverage/lcov.info
